eureka.instance.instance-id=${spring.application.name}:${random.int(10000,99999)}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Database
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
